export const cities = [
  { name: 'Beograd' },
  { name: 'Šid' },
  { name: 'Šabac' },
  { name: 'Čoka' },
  { name: 'Čačak' },
  { name: 'Čajetina' },
  { name: 'Užice' },
  { name: 'Ub' },
  { name: 'Subotica' },
  { name: 'Stara Pazova' },
  { name: 'Sremska Mitrovica' },
  { name: 'Sombor' },
  { name: 'Smederevo' },
  { name: 'Senta' },
  { name: 'Ruma' },
  { name: 'Raška' },
  { name: 'Požega' },
  { name: 'Požarevac' },
  { name: 'Plandište' },
  { name: 'Pećinci' },
  { name: 'Pančevo' },
  { name: 'Odžaci' },
  { name: 'Osečina' },
  { name: 'Opovo' },
  { name: 'Novi Sad' },
  { name: 'Novi Pazar' },
  { name: 'Novi Kneževac' },
  { name: 'Mionica' },
  { name: 'Ljig' },
  { name: 'Lučani u Guciji' },
  { name: 'Leskovac' },
  { name: 'Lajkovac' },
  { name: 'Kula' },
  { name: 'Kraljevo' },
  { name: 'Kosjerić' },
  { name: 'Kovačica' },
  { name: 'Kikinda' },
  { name: 'Kanjiža' },
  { name: 'Jagodina' },
  { name: 'Irig' },
  { name: 'Inđija' },
  { name: 'Ivanjica' },
  { name: 'Zrenjanin' },
  { name: 'Gornji Milanovac' },
  { name: 'Vršac' },
  { name: 'Vrnjačka Banja' },
  { name: 'Valjevo' },
  { name: 'Bela Crkva' },
  { name: 'Bajina Bašta' },
  { name: 'Arije' },
  { name: 'Apatin' },
  { name: 'Alibunar' },
  { name: 'Ada' },
  { name: 'Kruševac' },
  { name: 'Bačka Topola' },
  { name: 'Mali Iđoš' },
  { name: 'Preševo' },
  { name: 'Pirot' },
  { name: 'Dimitrovgrad' },
  { name: 'Bela Palanka' },
  { name: 'Babušnica' },
  { name: 'Prijepolje' },
  { name: 'Sečanj' },
  { name: 'Nova Crnja' },
  { name: 'Novi Bečej' },
  { name: 'Žitište' },
  { name: 'Vrbas' },
  { name: 'Bečej' },
  { name: 'Bačka Palanka' },
  { name: 'Paraćin' },
  { name: 'Kovin' },
  { name: 'Kragujevac' },
  { name: 'Niš' },
  { name: 'Temerin' },
  { name: 'Žabalj' },
  { name: 'Sremski Karlovci' },
  { name: 'Beočin' },
  { name: 'Bač' },
  { name: 'Bački Petrovac' },
  { name: 'Srbobran' },
  { name: 'Titel' },
  { name: 'Vranje' },
];
